# Generated by Django 5.1.4 on 2025-01-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailtrack_message_emailtrack_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtrack',
            old_name='emailsentdate',
            new_name='email_sent_date',
        ),
    ]
